---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ include "ovh-dynhost.fullname" . }}-config
  labels:
    {{- include "ovh-dynhost.labels" . | nindent 4 }}
data:
  DOMAIN: {{ .Values.dynhost.domain }}
